### ISSUE TITLE
About SHViT-s4 FLOPs

### ISSUE THREAD

**Issue by lewandofskee** [ysj9909/SHViT#4]
Thank you for your excellent work. However, when I reproduced it, I found that the FLOPs and Parmas of s1-s3 are consistent with the results in the paper. s4's Params are consistent with the paper but the FLOPs are only 789M while there are 986M in the paper, I'm not sure what the problem is? Looking forward to your reply.

**Comment by altair199797** [comment]
Are you running S4 on 256x256  input resolution?

**Comment by lewandofskee** [comment]
I found it, thanks for your reply.
